### ISSUE TITLE
Copy RDS snapshot tags

### ISSUE THREAD

**Issue by gustavo-eduard** [aws-solutions/instance-scheduler-on-aws#142]
create_rds_snapshot option is true, in RDS instance copy tags to snapshot is also set. Manually snapshots copy tags sucessfully, but with InstanceScheduler stop automation it doesn´t.

**Comment by lovepurohit** [comment]
Hi @gustavo-eduard 
Can you please check that you have sufficient permission attached to the IAM role of instance scheduler?

Thank you

**Comment by yprikhodko** [comment]
Steps to reproduce the issue:
1) create RDS instance with copy tags to snapshot option enabled 
2) set up instance scheduler to make a snapshot on instance stop
3) snapshot created with instance scheduler doesn't have any tags attached
At the same time if snapshot created manually (not via instance scheduler) tags are copied from RDS instance. 
It possibly happens because CreateDBSnapshot API call with Tags parameter overrides DB instance tags even if the source DB instance has the --copy-tags-to-snapshot (CopyTagsToSnapshot) option enabled(https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Tagging.html). 
Could you please have a look?

Thank you,
Yuriy

**Comment by praveenis** [comment]
Thanks Yuriy. With RDS services, tags are not copied by default when we stop RDS instance and create snapshot. Instance Scheduler solution is modeled on this RDS behavior, so this is an expected outcome. ‘CreateRDSSnapshot’ parameter allows users to utilize the option given by RDS service to create snapshot of RDS instances while stopping it.  Currently the tags are copied to snapshot if we take snapshot manually or through automatic back up settings. This request to copy tags for snapshots on stopping RDS instance will be a feature request and we will be adding it to out backlog.

Thanks,
Praveen

**Comment by rakshb** [comment]
We do not have plans to support this feature in the solution.
