### ISSUE TITLE
https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/scheduler-cli.zip downloads version 1.2.0 of scheduler-cli

### ISSUE THREAD

**Issue by sergii-maliarov-nordcloud** [aws-solutions/instance-scheduler-on-aws#278]
**Describe the bug**
https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/scheduler-cli.zip downloads version 1.200 of scheduler-cli

**To Reproduce**

1. Download https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/scheduler-cli.zip
2. Install it
3. `scheduler-cli --version` reports `scheduler-cli 1.2.0`

**Expected behavior**
https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/latest/scheduler-cli.zip downloads version 2.0.0 of scheduler-cli

**Please complete the following information about the solution:**
- [ ] Version: v2.0.0

**Additional context**
Also, would be nice to be able to download specific version, e.g. https://s3.amazonaws.com/solutions-reference/aws-instance-scheduler/1.3.3/scheduler-cli.zip should download version 1.3.3 of scheduler-cli

**Comment by hearde** [comment]
Fixed in [v1.5.1](https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1)

The links for downloading the CLI have changed. We now distribute a wheel and an sdist:

wheel: https://solutions-reference.s3.amazonaws.com/instance-scheduler-on-aws/latest/instance_scheduler_cli-1.5.1-py3-none-any.whl
sdist: https://solutions-reference.s3.amazonaws.com/instance-scheduler-on-aws/latest/instance_scheduler_cli-1.5.1.tar.gz
