### ISSUE TITLE
Cannot assign schedule per account

### ISSUE THREAD

**Issue by ashraf133** [aws-solutions/instance-scheduler-on-aws#287]
**Describe the bug**
Cannot assign schedule for a specific account

**To Reproduce**
Install, configure and run aws scheduler v2.0

**Expected behavior**
I can assign a specific schedule for a specific account

**Please complete the following information about the solution:**
-  Version: v2.0.0

**Comment by gockle** [comment]
Hi @ashraf133 If the requirement is to have a schedule specific to individual accounts, you can look into using Systems Manager > State Manager > Associations, You can start and stop instances in accounts based on CRON schedules. Since this feature is already available natively instance scheduler will not provide this feature.
