### ISSUE TITLE
AWS scheduler version update issue

### ISSUE THREAD

**Issue by gshetty437** [aws-solutions/instance-scheduler-on-aws#309]
Hi,

I have an AWS instance scheduler that was set up in 2018, and it's still running, but in the last few weeks, we are seeing issues where the scheduler is randomly sending STOP API calls after sending START API calls to the EC2. The issue is completely random and its doesn't have a fixed pattern. On consulting AWS support, they informed me it's a known issue and that updating the scheduler to the latest version will resolve the issue.

Thus I downloaded the latest CFN template and tried to update the existing CFN, while updating I saw the following resources were deleted, modified, and added. I'm entirely sure of the risk at hand here.

Resources being deleted,

ConfigTableAutoScalingReadTarget
ConfigTableAutoScalingWritePolicy
ConfigTableAutoScalingWriteTarget
ConfigurationTableAutoScalingReadPolicy
SchedulerDynamoDBScalingRole
SchedulerInvokePermission

Resources being modified,

ConfigTable
InstanceSchedulerSnsTopic
Main
SchedulerConfigHelper
SchedulerLogGroup
SchedulerPolicy
SchedulerRole

Resources being added,

EC2DynamoDBPolicy
Ec2PermissionsB6E87802
InstanceSchedulerEncryptionKeyAlias
InstanceSchedulerEncryptionKey
MaintenanceWindowTable
SchedulerRDSPolicy2E7C328A
SchedulerRoleDefaultPolicy66F774B8

Could you please answer my following queries,
1. Is the delete, modify and add expected? 
2. will my existing dynamoDb table be overridden because I have multiple schedules and period setup.
3.  Is there a better way to do it? or is it better to build the scheduler from scratch?

FYI, my current scheduler setup is 9 versions behind the latest version. also, my scheduler is deployed in the root account and the instances are in the child account, and there are around 500 instances that use this scheduler thus I'm being very cautious.

**Comment by gockle** [comment]
@gshetty437

1. Is the delete, modify and add expected, -- the delete section has resources that are currently not part of the latest version of the solution i.e the solution doesn't manage any auto scaling groups, so unsure how these resources have been part of your template. Add and modify are expected.

2. will my existing dynamoDb table be overridden because I have multiple schedules and period setup. -- no the solution will retain the data, unless the key=value structure of the older version is completely different to what is being setup in the latest version, either way its just safe to take a back up of the schedules.

3.  Is there a better way to do it? or is it better to build the scheduler from scratch? Can you create a new stack with the latest v1.4.0 version and copy the dynamoDB schedules to this new stack and disable active scheduling on the older stack. It's the safest option.
