### ISSUE TITLE
Error starting rds instance RDS:sandbox-trm-cp-0 (Shape is missing required key 'type'

### ISSUE THREAD

**Issue by vtx-rajravikumar** [aws-solutions/instance-scheduler-on-aws#331]
We have deployed Instance Scheduler version v1.4.0. We get the below error from some of the RDS instances. 
We see an [issue](https://github.com/aws-solutions/aws-instance-scheduler/issues/240) that was files for the previous releases regarding the same. 

`Error : ERROR   : Error starting rds instance RDS:sandbox-trm-cp-0 (Shape is missing required key 'type': OrderedDict([('members', OrderedDict([('SourceRegion', OrderedDict([('shape', 'String'), ('documentation', '<p>The ID of the region that contains the source for the db instance.</p>')]))]))]))`

**Comment by stepkirk** [comment]
Basically a +1 on this issue... we have been running 1.4.1 since 8/19 and we started receiving the errors shown above on 10/19.

**Comment by hearde** [comment]
It sounds like errors were being logged when the solution found an instance that could not be started/stopped (an instance that's a member of a multi-AZ cluster, Aurora serverless). This is expected, because the scheduler is unable to perform the requested action on the instance. Please reopen this issue if you are observing any other incorrect behavior.
