### ISSUE TITLE
Multiple Period not working

### ISSUE THREAD

**Issue by ku1918** [aws-solutions/instance-scheduler-on-aws#449]
Hi all,

I am trying to configure a scheduler that contain multiple period.

1. 9AM to 6PM 
2. 1130PM to 1230AM(next day)

The issue I am facing is the solution giving me "Any" State. Hence the scheduler is not working when i define multiple period.

My Config is as follow:
![image](https://user-images.githubusercontent.com/8154002/233141341-89b3fc1a-d548-4d74-859d-6da6a4dd7181.png)
![image](https://user-images.githubusercontent.com/8154002/233141416-dc8b0444-0b56-4627-861b-9dc819a59562.png)
![image](https://user-images.githubusercontent.com/8154002/233141106-04d12f00-0099-400b-8527-441b01e11513.png)

This is the logs
![image](https://user-images.githubusercontent.com/8154002/233141785-b4387ad9-817f-4124-a044-efd47947608f.png)

**Comment by CrypticCabub** [comment]
hi @ku1918, Thanks for reaching out!

This is a known issue that can occur when combining 1-sided start/stop periods with other periods. We're investigating possible solutions, but for now the current workaround would be to change your two midnight periods to be full periods instead of 1-sided (i.e. start 23:30, stop 24:00, and start 0:00 and stop 0:30). 

Please let us know if this does not work for you.

**Comment by ku1918** [comment]
@CrypticCabub , you mean the issue being 23:30 cross over the next day?

So I need to have 3 period under 1 schedule.
1. 9-6
2. 1130-12
3. 12-1230

Is that what you saying?

**Comment by CrypticCabub** [comment]
@ku1918, yes, you would need to have 3 periods like you describe to achieve the behavior you want.

The current scheduling logic looks at each day as individual a 24-hour periods. So to achieve a running period that crosses midnight you would need to have a running period at the end of the first day and at the start of the following day.
