### ISSUE TITLE
Multiple ssm maintenance windows for single schedule

### ISSUE THREAD

**Issue by Rithvik-Reddy-10** [aws-solutions/instance-scheduler-on-aws#457]
I am trying to create a schedule which spans across instances which have different maintenance windows. For example: We have 10 windows instance which have maintenance windows of 4 hours over weekend and 5 linux instances which have 1 hour maintenance window out of office hours. Can i add these two maintenance windows under single schedule in below format ? 

```
{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "UK-OfficeHours"
  },
  "description": {
    "S": "Office hours in UK Mon-Fri"
  },
  "enforced": {
    "BOOL": false
  },
  "hibernate": {
    "BOOL": false
  },
  "periods": {
    "SS": [
      "UK-OfficeHours-period"
    ]
  },
  "retain_running": {
    "BOOL": false
  },
  "ssm_maintenance_window": {
    "S": "ec2-maintenance-linux,ec2-maintenance-windows"
  },
  "stop_new_instances": {
    "BOOL": true
  },
  "timezone": {
    "S": "Europe/London"
  },
  "use_maintenance_window": {
    "BOOL": true
  }
}
```

Please Advice. 
Thanks

**Comment by CrypticCabub** [comment]
Hi @Rithvik-Reddy-10 

Schedules currently only support a single ssm_maintenance_window per schedule so you would need to create a separate schedule for your windows and linux instances. 

Even if the scheduler did support it, I would still recommend creating separate schedules so that you can avoid errantly starting (and paying for) your linux instances during the windows maintenance window and vice-versa

**Comment by richardsonky** [comment]
i agree it would be useful to configure multiple maint windows in the same schedule.  another alternative would be to look for the maint window that applies to that ec2 and start it.  otherwise we have to create multiple schedules with different tags which can confuse some users if they happen to tag the instance with the wrong schedule that doesn't correspond to the maint window.

**Comment by rakshb** [comment]
We do not have plans to support this feature in the solution.
