### ISSUE TITLE
Lambda not logging if Cloudwatch Log Group Name too long

### ISSUE THREAD

**Issue by ku1918** [aws-solutions/instance-scheduler-on-aws#464]
I encounter a weird issue when the lambda instance scheduler not logging anything if the cloudwatch log group name is too long.

I am scheduler around 50+ account under the organization.

I notice Scheduler-ec2-account-1-ap-southeast-1-20230614 works fine.
But once Scheduler-ec2-<account-1 until account 50>-ap-southeast-1-20230614 , the logs not coming in anymore.

Any thought on how I can omit the accounts ID from the log group name?

Thanks.

**Comment by CrypticCabub** [comment]
Hi @ku1918 

Do you happen to have local scheduling disabled? ("This account" in the CFN config).

The issue you describe is a known bug that will be fixed in our next patch release. When local account scheduling is disabled, the scheduler can sometimes incorrectly group multiple accounts together in the same execution and cause the log group behavior you are describing. The workaround would be to enable local account scheduling (even if you do not have any tagged instances on the hub account) as the bug should only occur when that setting is disabled.

**Comment by hearde** [comment]
Fixed in https://github.com/aws-solutions/instance-scheduler-on-aws/releases/tag/v1.5.1
