### ISSUE TITLE
Scheduler config is not honored and default is used

### ISSUE THREAD

**Issue by peter-kmec-mox** [aws-solutions/instance-scheduler-on-aws#475]
**Describe the bug**

After 1.5.1 config from DynamoDB is not read, instead only global (lambda env) config is used.

**To Reproduce**

Use separate config in 1.5.1 version and it will not take effect. 

**Expected behavior**

If there is additional configuration apart default defined, it should take priority 

**Please complete the following information about the solution:**

- [x] Version: [v1.5.1]

**Additional context**
[Add any other context about the problem here.] 
Recent Change: (https://github.com/aws-solutions/instance-scheduler-on-aws/blame/fd54810be022742639cc7fe1ba32a13750424f92/source/app/instance_scheduler/configuration/scheduler_config_builder.py#L89)

**Comment by hearde** [comment]
This is an intentional change. To change the scheduler configuration, modify the cloudformation parameter values and update the stack. The dynamodb fields for global configuration will be removed in a future release.

When updating the stack, the prior and current behavior is to wipe out all custom configuration and replace it with the cloudformation parameter values (except for the remote account IDs), so configuring directly in dynamodb was always a little risky. An alternative is to modify the environment variables directly, though this creates drift and it has the same problem as dynamodb: it will be overwritten whenever the stack is updated.
