### ISSUE TITLE
Scheduler can't see the RDS Instance and Schedulable Instances

### ISSUE THREAD

**Issue by asoltes** [aws-solutions/instance-scheduler-on-aws#567]
**Describe the bug**

I installed the instance scheduler in our 2 aws accounts to save cost and unfortunately the scheduler can't see the RDS instances and schedulable instances, I tried the tags to an EC2 instance and it works, I checked the cloudtrail and look for the event the iam role created and don't see any problem. I also checked the permissions in kms and describe and get permissions and it looks good to me. Please see the screenshot below.

**To Reproduce**

**Expected behavior**

**Please complete the following information about the solution:**

- [x] Version: [e.g. v3.0.3]

- [x] Region: [e.g. ap-southeast-1]
- [ ] Was the solution modified from the version published on this repository? **NO**

- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for
      the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?
I can't see any errors in cloudwatch logs and checked all the tags and it was configured correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/f5ab8163-c3c6-4e3b-bf40-50c0fc0b4c71)

**Comment by CrypticCabub** [comment]
what do the RDS scheduler logs show? These can be found within a log-group named `{stack-name}-scheduler-logs` and have are named Scheduler-{service}-{account}-{region}-{date}

**Comment by asoltes** [comment]
here's the logs for the RDS
![image](https://github.com/user-attachments/assets/2a71d06e-9f1b-4db8-9f4a-60c070c0c860)

**Comment by CrypticCabub** [comment]
Looks like the instance is indeed not being returned to the scheduler logic as you say. A few things to confirm:

- What type of instance are you trying to schedule? (rds, aurora, neptune, docdb? what database engine?)
- Does the tag key on the instance exactly match the tag key specified on the hub stack parameters?
- what services are enabled on the solution hub stack?
- in the case of a cluster, where is the tag located? on the parent cluster, or on one of the instances?

Most likely the filters being passed to the ResourcesGroupsTaggingAPI (how we discover RDS instances) are causing your instance to be overlooked, so the above information should help identify why this may be happening.

**Comment by asoltes** [comment]
- It was RDS with PostgreSQL 
- The TagKey set was the default which is `Schedule` and as I did the testing it was working in EC2 but not in RDS 
- In stack I enabled ec2 and rds
- I'm not using the cluster in this account as this was only for qa's testing.

I looked on every logs even in cloudtrail and I can't see any problem with my setup. what do I need to check on `ResourcesGroupsTaggingAPI` ?

**Comment by CrypticCabub** [comment]
There nothing I'm aware of that you should have to do for the ResourceGroupsTaggingAPI, that's just the internal API we use on the solution to discover your instances. All of my testing indicates that what you have should work so let's validate some assumptions:

Solution Hub Stack:
- Installed in: Account A / ap-southeast-1
- EC2 Scheduling: enabled
- RDS Scheduling: enabled
- ScheduledRegions: ap-southeast-1
- namespace: "myValue"
- useAwsOrganizations: False
- principals: [Account B]

Solution Spoke Stack:
- Installed in: Account B / ap-southest-1
- namespace: "myValue" (same as hub)
- useAwsOrganizations: False (same as hub)

RDS Instance:
- located in: Account A / ap-southeast-1 
- Standard RDS instance, PostgreSQL engine
- tagged with `Schedule: myScheduleName`
- in state: "available"

of particular interest would be the current state of the RDS instance as I know we do some pre-filtering down to only "schedulable" states which may come into play here, but otherwise the logs you shared do not indicate any errors are occuring so the majority of the solution appears to be configured correctly

**Comment by CrypticCabub** [comment]
closing as stale. Please re-open if you are still having issues
