### ISSUE TITLE
Remote Client Failing to Register in CloudWatch Logs Master

### ISSUE THREAD

**Issue by neilromatowski0373** [aws-solutions/instance-scheduler-on-aws#568]
Hi,

We have followed our standard process to add new accounts to the stack by way of update to the CF template. There are no issues reported and we can see the account ID in the remote_account_ids field in the Dynamo DB Config field. The instance does not appear in the CloudWatch Logs - ec2-instance-scheduler-master-logs. I have tried removing and re-adding but this has made no difference. Can you advise how we can further investigate this.

Many thanks.

Neil.

**Comment by CrypticCabub** [comment]
I'll assume that this is for the v3.0.3 release of the solution. If you are on a different version this same procedure should still work but the log stream names may be different.

Take a look in the `{stack-name}-scheduler-logs` log group in CloudWatch and look for logs matching `Scheduler-{service}-{account}-{region}-{date}` for the new account you just on-boarded. you can also look at the `SchedulingOrchestratorHandle-{date}` logs to see if there were any issues loading schedules or initializing scheduling events for on-boarded accounts.

**Comment by neilromatowski0373** [comment]
Thanks CrypticCabub. We are still on v1.5.1. I have checked the scheduler logs and cannot find a log group for EC2 for the account we created. I also cannot find the log group SchedulingOrchestratorHandler-{date}. Has this come after v1.5.1. I wonder if we should update the stack? Thanks.

**Comment by CrypticCabub** [comment]
in 1.5.1 I believe the orchestrator logs are named CloudWatchEventHandler logs

If there are no scheduler logs for the new account created, then I suspect there's a problem in the account registration. In 1.5.1 I know there was a behavior that would deregister an account if the role was inaccessible so it's possible that you just need to re-do the stack update and double check that the account-id is actually registered in the solution's config table.

v3.0.x removed the behavior because of exactly this sort of scenario. It also includes much better logging for scheduling decisions along with a number of bugfixes and security improvements, so I would recommend upgrading as soon as you are able.

**Comment by neilromatowski0373** [comment]
I cannot locate the log file above. I have cloned the repository in GitHub but cannot locate a CFN template. I have tried the links here https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/aws-cloudformation-templates.html but just get a browser message with this site cannot be reached.

**Comment by CrypticCabub** [comment]
Are you still getting that browser error? My browser is able to download the CFN templates from the link you provided just fine, so mabe there's a security setting somewhere preventing access for you?

The github repo does not provide CFN templates as they have to be generated within the context of a specific host. The readme on the repo explains how you can deploy directly from the repo using `cdk deploy` or create your own templates using the `build-s3-dist.sh` script


And just in case it wasn't clear, the cloudwatch event logs file would be a log-stream within the `{stackname}-scheduler-logs` log group

**Comment by neilromatowski0373** [comment]
Thanks for your help CrypticCabub. Seems to have kicked into life. I will however look to update as well.
