### ISSUE TITLE
Cross-Account Instance Scheduler StateTable out of sync showing running resource as Stopped. This causes the instance to never be powered off at the configured schedule.

### ISSUE THREAD

**Issue by samumill** [aws-solutions/instance-scheduler-on-aws#592]
**Background**
We are using the AWS Instance Scheduler to turn off EC2 instances at specified hours of the day. We have 24 schedules, each corresponding to an hour of the day (UTC timezone). 

These schedules simply turn off resources at the corresponding time. They do not turn them back on. Rather, users are expected to turn their resources back on as needed. 

We have this solution configured as a cross-account solution using our AWS Organization ID per (https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/cross-account-instance-scheduling-using-account-ids-or-aws-organization-id.html)

**Issue**
A user in our organization changed their schedule from poweroff-at-23-utc to poweroff-at-0-utc. They reported that after doing so, their EC2 instance was never powered off. After verifying that the schedules were working for other resources, it was discovered that the **StateTable** showed this EC2 instances as **Stopped** when in reality it was running

At some point, something has occurred causing the state table to become out of sync with reality. This would explain why the EC2 instances was never being powered off, as the Instance Scheduler believed it was already powered off.

Looking at the CloudWatch instance-scheduler-logs I am seeing no mention of the Instance ID of this resource after 2024-11-26. The InstanceScheduler-LastAction tag says this resources was last stopped on 2024-11-24 23:00UTC (one day prior). 

Furthermore, looking at the EC2 Instance's audit logs, I can see the user changed their schedule at 2024-11-25T22:49:22Z. It looks like moments later, the **default-Scheduler-Role-<account_id>-us-east-1** proceeded to power off the resource following the **old** schedule at 2024-11-25T23:00:22Z. The user the manually turned their resource back on at 2024-11-25T23:07:01Z (7 minutes later).

**Hypothesis**
The InstanceSchedule is configured to run every 30 minutes. It looks like the user changed their schedule tag at 22:49 UTC from poweroff-at-23-utc to poweroff-at-0-utc. Even still, it would appear the Instance Scheduler honored the old poweroff-at-23-utc schedule, shutting down the resource at 23:00 UTC. Shortly thereafter, the user powered their EC2 instance back on at 23:07 UTC. Perhaps this caused some sort of race condition where the Instance Scheduler lambda was still running/updating the StateTable to say the instance was "stopped" right when the user was starting the instance?

**Hub/Master Instance Scheduler Configuration Details**
- Version: (SO0030) instance-scheduler-on-aws v3.0.5
- Region: us-east-1
- No modifications made to CloudFormation template
- No CloudWatch errors to be found (see note above under **Issue**)

**Remote Instance Scheduler Configured Details**
- Version: (SO0030S) instance-scheduler-on-aws remote v3.0.5
- Region: us-east-1
- No modifications made to CloudFormation template

**Comment by CrypticCabub** [comment]
Hi @samumill

Thanks for reporting this. 1-sided stop periods not working at midnight is a known issue, though the reason is not because of the state table.

To clarify, the state table tracks the last desired state of an instance when the scheduler ran, NOT the current running state of the instance in reality. The real reason why 1-sided stop periods do not work at midnight is because the period is essentially overlapping with itself. a 1-sided stop period paints the first half of the day with an "any" state that prevents any action from being taken, and the back half with a "stopped" state. The transition from "any" to "stopped" is what triggers Instance Scheduler to actually perform the stop action. putting a 1-sided stop period at 0:00 or 23:59 will paint the entire timeline of the day with either any or stopped, with no transitions occuring at any point during the day. This results in the schedule failing to perform any actions at all. 

To get around this, you must leave room for at least 1 scheduling cycle to occur at the end/beginning of the day in a different state for a state transition. one way you could achieve this and still have a midnight stop is to use a different time zone for that particular schedule to ensure that the midnight stop in your desired timezone is occuring at say 10pm in the schedule's time zone.

We have an open backlog item to identify potential fixes to the root cause of this problem, but for the present this is the best work around that I am aware of.
